=== kingof7/JavaScript-DOM-KITRI/WebContent/AJAX/XML/responseXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.example.org/responseXML"
			 xmlns="http://www.example.org/responseXML" 
			 elementFormDefault="qualified">
	<xsd:element name="member" type="member"/>
	
	<xsd:complexType name="member">
		<xsd:sequence>
			<xsd:element name="student" minOccurs="1" maxOccurs="unbounded" type="student"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="student">
		<xsd:sequence>
			<xsd:element name="stdNumber" minOccurs="1" maxOccurs="1" type="xsd:string"/>
			<xsd:element name="stdName" minOccurs="1" maxOccurs="1" type="xsd:string"/>
			<xsd:element name="score" minOccurs="1" maxOccurs="1" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== kingof7/JavaScript-DOM-KITRI/WebContent/AJAX/responseXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<member xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://www.example.org/responseXML responseXML.xsd"
			 xmlns="http://www.example.org/responseXML">
	<student>
		<stdNumber>1001</stdNumber>
		<stdName>홍길동</stdName>
		<score>95</score>
	</student>

	<student>
		<stdNumber>1002</stdNumber>
		<stdName>김길동</stdName>
		<score>90</score>
	</student>
	
	<student>
		<stdNumber>1003</stdNumber>
		<stdName>박길동</stdName>
		<score>80</score>
	</student>
</member>
